- action:
  - data:
      message: Dags att vattna
    service: notify.telegram_jocke
  - service: rest_command.vatten_larm_vera
  alias: ikea
  condition: []
  id: '1525982778519'
  trigger:
  - entity_id: binary_sensor.water_sensor_2_3
    from: 'off'
    platform: state
    to: 'on'
- id: '1526639185280'
  alias: Påminnelse Gardin
  trigger:
  - at: '21:15'
    platform: time
  condition: []
  action:
  - data:
      message: Drar ner gardin om 15 minuter
    service: notify.telegram_jocke
  - data:
      message: Drar ner gardin om 15 minuter
    service: notify.telegram_helena
- alias: Notification Audio - Test
  trigger:
  - platform: state
    entity_id: input_boolean.test_audio_notification
    from: 'off'
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.say
    data_template:
      variables:
        master: media_player.sovrum
        where: media_player.badrum, media_player.matrum, media_player.sovrum
        volume: '.3'
        what: Rullgardinen åker ner om 15 minuter
  - delay: 00:00:01
  - service: homeassistant.turn_off
    entity_id: input_boolean.test_audio_notification
  id: 0f86a05e2da44b099a7341a8bf009a29
- alias: 'TeleBot: Plafonnier'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram_jocke
    data_template:
      message: Pong =)
  id: e905d36d9b714c269109322cfae3f1dd
- alias: telegram bot that replies the temprature
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /temp
  action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: Nuvarande lägsta temperatur, {{ states.sensor.temp_altan_222.state
        }}°C
      disable_notification: true
  id: 44a9a9b0190a498ab712ef389c3b783b
- alias: CarPresence_ON
  trigger:
    platform: state
    entity_id: binary_sensor.CarPresence
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: closed
  action:
  - service: cover.open_cover
    entity_id: cover.garage_door
  id: b41380606cdd4dd8a9540c6cb08ac062
- alias: CarPresence_OFF
  trigger:
    platform: state
    entity_id: binary_sensor.CarPresence
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: cover.close_cover
    entity_id: cover.garage_door
  id: c92e369f738d4410b4d8cd116f6427e0
- action:
  - data:
      message: hejdå
    service: notify.telegram_jocke
  - data:
      message: Tackar ! Älskar dig
    service: notify.telegram_helena
  alias: hejdå
  condition: []
  id: '1535112441251'
  trigger:
  - entity_id: binary_sensor.carpresence
    platform: state
    to: 'off'
- action:
  - data:
      message: Välkommen till villa moga
    service: notify.telegram_jocke
  - data:
      message: Jocke är vid porten. Lite hjälp kanske ?
    service: notify.telegram_helena
  alias: Välkommen
  condition: []
  id: '1535114635500'
  trigger:
  - entity_id: binary_sensor.carpresence
    platform: state
    to: 'on'
- action:
  - data:
      message: tack
    service: notify.telegram_jocke
  alias: vattnat
  condition: []
  id: '1537884975135'
  trigger:
  - entity_id: binary_sensor.water_sensor_2_3
    from: 'on'
    platform: state
    to: 'off'
- id: '1537902808015'
  alias: ''
  trigger: []
  condition: []
  action: []
- action:
  - data:
      message: 'Ny uppdatering till hass hemma '
    service: notify.telegram_jocke
  alias: Update-Notify
  condition: []
  id: '1537979871607'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: 95% klart på utskriften
    service: notify.telegram_jocke
  alias: printer
  condition: []
  id: '1541949682710'
  trigger:
  - entity_id: sensor.printer
    platform: state
    to: '95'
- id: '1541970471813'
  alias: 3d pwr off 100%
  trigger:
  - entity_id: sensor.printerprogress
    from: '99'
    platform: state
    to: '100'
  condition: []
  action:
  - data:
      message: Färdig med utskriften. Stänger av om 5 minuter
    service: notify.telegram_jocke
  - delay: 00:05:00
  - data:
      entity_id: switch.skrivaren_326
    service: switch.turn_off
  - data:
      entity_id: switch.printerlight
    service: switch.turn_off
- action:
  - data:
      payload_template: '{{ states(''sensor.sparsnas_energy_consumption_over_time'')
        }}'
      retain: 'true'
      topic: template/kwh/month
    service: mqtt.publish
  alias: Sparsnäs monthly consumption
  trigger:
    platform: time
    at: 00:00:01
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ now().day | string == "1" }}'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ now().month | string == "1" }}'
      - condition: template
        value_template: '{{ now().month | string == "2" }}'
      - condition: template
        value_template: '{{ now().month | string == "3" }}'
      - condition: template
        value_template: '{{ now().month | string == "4" }}'
      - condition: template
        value_template: '{{ now().month | string == "5" }}'
      - condition: template
        value_template: '{{ now().month | string == "6" }}'
      - condition: template
        value_template: '{{ now().month | string == "7" }}'
      - condition: template
        value_template: '{{ now().month | string == "8" }}'
      - condition: template
        value_template: '{{ now().month | string == "9" }}'
      - condition: template
        value_template: '{{ now().month | string == "10" }}'
      - condition: template
        value_template: '{{ now().month | string == "11" }}'
      - condition: template
        value_template: '{{ now().month | string == "12" }}'
  id: '1516722867362'
- action:
  - data:
      payload_template: '{{ states(''sensor.sparsnas_energy_consumption_over_time'')}}'
      retain: 'true'
      topic: template/kwh/day
    service: mqtt.publish
  alias: Sparsnäs daily consumption
  condition: []
  id: '1516806539856'
  trigger:
  - at: 00:00:02
    platform: time
- action:
  - data:
      entity_id: automation.sparsnas_daily_consumption
    service: automation.trigger
  - data:
      entity_id: automation.sparsnas_monthly_consumption
    service: automation.trigger
  alias: trigger-sparsnas-if-unknown
  condition:
  - condition: state
    entity_id: sensor.sparsnas_template_kwh_sensor_month
    state: Unknown
  id: '1519996400010'
  trigger:
  - entity_id: sensor.sparsnas_energy_consumption_over_time
    from: unknown
    platform: state
- id: '1542913726018'
  alias: tänd när vi kommer hem
  trigger:
  - entity_id: device_tracker.helenas_mobil
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.joakims_mobil
    from: not_home
    platform: state
    to: home
  condition:
  - after: '14:00'
    before: '21:00'
    condition: time
  action:
  - data:
      entity_id: scene.belysning_kvall_pa
    service: scene.turn_on
- id: '1543786588685'
  alias: 'På minnelse dammsugning '
  trigger:
  - at: '19:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: time
    weekday:
    - sun
    - tue
    - thu
  action:
  - data:
      message: Dammsugning imorgon
    service: notify.telegram_jocke
  - data:
      message: Dammsugning imorgon
    service: notify.telegram_helena
- id: '1543787373178'
  alias: Dammsugning
  trigger:
  - at: '10:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: time
    weekday:
    - mon
    - wed
    - fri
  action:
  - service: vacuum.turn_on
- id: '1543951030518'
  alias: print-light-on
  trigger:
  - event_data:
      command: /p1
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.printerlight
    service: switch.turn_on
  - data:
      message: Tänder belysningen vid skrivaren
    service: notify.telegram_jocke
- id: '1543951370906'
  alias: print-light-off
  trigger:
  - event_data:
      command: /p0
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.printerlight
    service: switch.turn_off
  - data:
      message: Släcker belysningen vid skrivaren
    service: notify.telegram_jocke
- id: '1544217865116'
  alias: expriment router
  trigger:
  - entity_id: binary_sensor.expriment_knapp
    for:
      hours: 0
      minutes: 10
      seconds: 0
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: 'Inget internet. Startar om router '
    service: notify.telegram_jocke
  - data:
      entity_id: switch.printerlight
    service: switch.turn_off
  - delay: 00:05:00
  - data:
      entity_id: switch.printerlight
    service: switch.turn_on
