- action:
  - data:
      message: Dags att vattna
    service: notify.telegram_jocke
  - service: rest_command.vatten_larm_vera
  alias: ikea
  condition: []
  id: '1525982778519'
  trigger:
  - entity_id: binary_sensor.water_sensor_2_3
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Drar ner gardin om 15 minuter
    service: notify.telegram_jocke
  alias: P책minnelse Gardin
  condition: []
  id: '1526639185280'
  trigger:
  - at: '21:15'
    platform: time
- action:
  - data:
      message: helena kommer hem
    service: notify.telegram_jocke
  - data:
      master: media_player.Sovrum
    entity_id:
    - media_player.Badrum
    - media_player.Matrum
    service: media_player.sonos_join
  - delay: '10'
  - data:
      message: Helena kommer hem!
      sonos_entity: media_player.Sovrum
      volume: '0.5'
    service: script.sonos_say
  alias: Helena Kommer hem
  condition: []
  id: '1527013839788'
  trigger:
  - entity_id: device_tracker.joakims_mobil
    from: not_home
    platform: state
    to: home
- alias: Notification Audio - Test
  trigger:
  - platform: state
    entity_id: input_boolean.test_audio_notification
    from: 'off'
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.say
    data_template:
      variables:
        master: media_player.sovrum
        where: media_player.badrum, media_player.matrum, media_player.sovrum
        volume: '.3'
        what: Rullgardinen 책ker ner om 15 minuter
  - delay: 00:00:01
  - service: homeassistant.turn_off
    entity_id: input_boolean.test_audio_notification
- alias: 'TeleBot: Plafonnier'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram_jocke
    data_template:
      message: Pong =)
- alias: telegram bot that replies the temprature
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /temp
  action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: Nuvarande l채gsta temperatur, {{ states.sensor.temp_altan_222.state
        }}째C
      disable_notification: true
