- action:
  - data:
      message: Dags att vattna
    service: notify.telegram_jocke
  - service: rest_command.vatten_larm_vera
  alias: ikea
  condition: []
  id: '1525982778519'
  trigger:
  - entity_id: binary_sensor.water_sensor_2_3
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Drar ner gardin om 15 minuter
    service: notify.telegram_jocke
  - data:
      message: Drar ner gardin om 15 minuter
    service: notify.telegram_helena
  alias: Påminnelse Gardin
  condition: []
  id: '1526639185280'
  trigger:
  - at: '21:15'
    platform: time
- action:
  - data:
      message: helena kommer hem
    service: notify.telegram_jocke
  - data:
      master: media_player.Sovrum
    entity_id:
    - media_player.Badrum
    - media_player.Matrum
    service: media_player.sonos_join
  - delay: '10'
  - data:
      message: Helena kommer hem!
      sonos_entity: media_player.Sovrum
      volume: '0.5'
    service: script.sonos_say
  alias: Helena Kommer hem
  condition: []
  id: '1527013839788'
  trigger:
  - entity_id: device_tracker.joakims_mobil
    from: not_home
    platform: state
    to: home
- alias: Notification Audio - Test
  trigger:
  - platform: state
    entity_id: input_boolean.test_audio_notification
    from: 'off'
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.say
    data_template:
      variables:
        master: media_player.sovrum
        where: media_player.badrum, media_player.matrum, media_player.sovrum
        volume: '.3'
        what: Rullgardinen åker ner om 15 minuter
  - delay: 00:00:01
  - service: homeassistant.turn_off
    entity_id: input_boolean.test_audio_notification
- alias: 'TeleBot: Plafonnier'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram_jocke
    data_template:
      message: Pong =)
- alias: telegram bot that replies the temprature
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /temp
  action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: Nuvarande lägsta temperatur, {{ states.sensor.temp_altan_222.state
        }}°C
      disable_notification: true
- alias: CarPresence_ON
  trigger:
    platform: state
    entity_id: binary_sensor.CarPresence
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: closed
  action:
  - service: cover.open_cover
    entity_id: cover.garage_door
- alias: CarPresence_OFF
  trigger:
    platform: state
    entity_id: binary_sensor.CarPresence
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: cover.close_cover
    entity_id: cover.garage_door
- action:
  - data:
      message: hejdå
    service: notify.telegram_jocke
  - data:
      message: Tackar ! Älskar dig
    service: notify.telegram_helena
  alias: hejdå
  condition: []
  id: '1535112441251'
  trigger:
  - entity_id: binary_sensor.carpresence
    platform: state
    to: 'off'
- action:
  - data:
      message: Välkommen till villa moga
    service: notify.telegram_jocke
  - data:
      message: Jocke är vid porten. Lite hjälp kanske ?
    service: notify.telegram_helena
  alias: Välkommen
  condition: []
  id: '1535114635500'
  trigger:
  - entity_id: binary_sensor.carpresence
    platform: state
    to: 'on'
- action:
  - data:
      message: tack
    service: notify.telegram_jocke
  alias: vattnat
  condition: []
  id: '1537884975135'
  trigger:
  - entity_id: binary_sensor.water_sensor_2_3
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.espeasy
    service: switch.turn_on
  - delay: 00:30:00
  - data:
      message: släcker strax
    service: notify.telegram_jocke
  - data:
      entity_id: switch.espeasy
    service: switch.turn_off
  alias: esp.test.on
  condition: []
  id: '1537902808015'
  trigger:
  - entity_id: binary_sensor.expriment_knapp
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: 'Ny uppdatering till hass hemma '
    service: notify.telegram_jocke
  alias: Update-Notify
  condition: []
  id: '1537979871607'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: 95% klart på utskriften
    service: notify.telegram_jocke
  alias: printer
  condition: []
  id: '1541949682710'
  trigger:
  - entity_id: sensor.printer
    platform: state
    to: '95'
- action:
  - data:
      message: Färdig med utskriften. Stänger av om 5 minuter
    service: notify.telegram_jocke
  - delay: 00:05:00
  - data:
      entity_id: switch.skrivaren_326
    service: switch.turn_off
  alias: skrivaren klar
  condition: []
  id: '1541970471813'
  trigger:
  - entity_id: sensor.printerprogress
    from: '99'
    platform: state
    to: '100'
- action:
  - data:
      entity_id: switch.espeasy
    service: switch.turn_on
  alias: expriment knapp
  condition: []
  id: '1542125454618'
  trigger:
  - entity_id: binary_sensor.expriment_knapp
    from: 'off'
    platform: state
    to: 'on'
