################################################################################
# House.Mode                                                                   #
#                                                                              #
# Source: https://                                                             #
#                                                                              #
################################################################################


################################################################################
#                                                                          Div #
################################################################################





################################################################################
#                                                                        Group #
################################################################################

group:

################################################################################
#                                                                       switch #
################################################################################

switch:

################################################################################
#                                                                      sensors #
################################################################################

sensor:

################################################################################
#                                                                  Automations #
################################################################################

automation:
