################################################################################
# House.Mode.Package                                                           #
# Made By: Joakim Engberg                                                      #
# Source:                                                                      #
# https://github.com/joaeng/backuphome/blob/master/packages/housemode.yaml     #
################################################################################


################################################################################
#                                                                configuration #
################################################################################

input_boolean:
  status:
    name: Närvaro
    initial: off

################################################################################
#                                                                        Group #
################################################################################

group:
  status:
    name: Närvaro
    view: yes
    entities:
    - sensor.housemode
    - input_boolean.status

################################################################################
#                                                                       switch #
################################################################################

#switch:

################################################################################
#                                                                      sensors #
################################################################################

sensor:
  - platform: template
    sensors:
      housemode:
          value_template: >-
            {% if is_state("input_boolean.status","off") %}
              away
            {% else %}
              home
            {% endif %}

################################################################################
#                                                                  Automations #
################################################################################

automation:

  alias: testning away
  trigger:
    - at: '19:45'
      platform: time
  condition:
    - condition: state
      entity_id: sensor.housemode
      state: away
  action:
    - data:
        message: testar away
      service: notify.telegram_jocke


  alias: testning home
  trigger:
    - at: '19:50'
      platform: time
  condition:
    - condition: state
      entity_id: sensor.housemode
      state: home
  action:
    - data:
        message: testar home
      service: notify.telegram_jocke
