################################################################################
# House.Mode                                                                   #
#                                                                              #
# Source: https://                                                             #
#                                                                              #
################################################################################


################################################################################
#                                                                configuration #
################################################################################

input_boolean:
  status:
    name: Närvaro
    initial: off

################################################################################
#                                                                        Group #
################################################################################

group:
  status:
    name: Närvaro
    view: yes
    entities:
    - sensor.housemode
    - input_boolean.status

################################################################################
#                                                                       switch #
################################################################################

#switch:

################################################################################
#                                                                      sensors #
################################################################################

sensor:
  - platform: template
    sensors:
      housemode:
          value_template: >-
            {% if is_state("input_boolean.status","off") %}
              away
            {% else %}
              home
            {% endif %}

################################################################################
#                                                                  Automations #
################################################################################

automation:
