################################################################################
# House.Mode.Package                                                           #
# Made By: Joakim Engberg                                                      #
# Source:                                                                      #
# https://github.com/joaeng/backuphome/blob/master/packages/leave.yaml     #
################################################################################

################################################################################
#                                                                configuration #
################################################################################



################################################################################
#                                                                        Group #
################################################################################

group:
  leave:
    name: leave
    view: no
    entities:
      - device_tracker.helenas_mobil
      - device_tracker.joakims_mobil
      - automation.helena_lamnar
      - automation.jocke_lamnar

################################################################################
#                                                                       switch #
################################################################################

#switch:

################################################################################
#                                                                      sensors #
################################################################################

sensor:

################################################################################
#                                                                  Automations #
################################################################################

automation:
  - alias: jocke_lämnar
    trigger:
    - entity_id: device_tracker.joakims_mobil
      from: home
      platform: state
      to: not_home
    condition:
    - condition: state
      entity_id: device_tracker.helenas_mobil
      state: not_home
    action:
    - data:
        message: Du gick sist .. Men larmade du?
      service: notify.telegram_jocke

  - alias: helena_lämnar
    trigger:
    - entity_id: device_tracker.helenas_mobil
      from: home
      platform: state
      to: not_home
      for:
        minutes: 10
    condition:
    - condition: state
      entity_id: device_tracker.joakims_mobil
      state: not_home
    - condition: state
      entity_id: binary_sensor.verisure_113
      state: 'off'

    action:
    - data:
        message: Du gick sist .. Men larmade du?
      service: notify.telegram_helena



################################################################################
#                                                                       script #
################################################################################

script:
